---
Name: ss-logger
After:
  - "#framework"
  - "#cms"
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - CatchDesign\SSLogger\CLogConfExt
SilverStripe\Assets\File:
  extensions:
    - CatchDesign\SSLogger\AssetLogFileExt
